version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Hello  
          command: |
            echo "Echo environment" 
            env
workflows:
  say-hello:
    jobs:
      - hello-job
